app:
  auth:
    tokenSecret: JWTSuperSecretKey
    tokenExpirationMsec: 604800000
  oauth2:
    authorizedRedirectUris:
      - https://coderunner.tcomad.tk/login

server:
  tomcat:
    internal-proxies: .*
    uri-encoding: UTF-8
  forward-headers-strategy: native

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  http:
    encoding:
      charset: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          facebook:
            redirectUri: "https://rue.tcomad.tk/oauth2/callback/{registrationId}" # Note that facebook now mandates the use of https redirect URIs, so make sure your app supports https in production
            scope:
              - email
              - public_profile