server:
  port: 8090

app:
  auth:
    tokenSecret: ac2047c3edbed889779dc23594992f56709cf501e55e5e822e571ba442fb32c4
    tokenExpirationMsec: 604800000

aws:
  enabled: true
  accessKey: AKIA6PLEN54HD4FRVEHZ
  secretKey: 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
  bucketName: coderunner-bucket
  bucketAddress: https://coderunner-bucket.s3.us-east-2.amazonaws.com

settings:
  front-url: https://coderunner.tcomad.tk

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: cmpskhpi
    password: '!In19fiZ30$ComP19*modelIng64^'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-prod.cdtkmiuurwsr.us-east-2.rds.amazonaws.com:3306/Coderunner?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: admin
    password: b563a80c0a4247ec074ca2e6e7b9a394
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 848358615623604
            clientSecret: 2dd7d5366c61894eb4d0b8ae336a685c
